# -*- coding: utf-8 -*-
"""YOLOv4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hfmMJfmJdiTIjbC5bF4RE7_LJDdk1yYD
"""

#Md. najmul Huda Hridoy
#15-15-513
#Daffodil International University

# clone darknet repo
! git clone https://github.com/AlexeyAB/darknet

# Commented out IPython magic to ensure Python compatibility.
# change makefile to have GPU and OPENCV enabled
# %cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile

# verify CUDA
!/usr/local/cuda/bin/nvcc --version

# make darknet (builds darknet so that you can then use the darknet executble file to run or train object detectors)
!make

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights

# Commented out IPython magic to ensure Python compatibility.
# define helper functions
def imShow(path):
  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plt.gcf()
  fig.set_size_inches(18,10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

# use this to upload files
def upload():
  from google.colab import files
  uploaded = files.upload()
  for name, data in uploaded.items():
    with open(name, 'wb') as f:
      f.write(data)
      print ('saved file', name)

#use this to download a file
def download(path):
  from google.colab import files
  files.download(path)

# run darknet detection on test images
!./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/dog.jpg

# show image using our helper function
imShow('predictions.jpg')

# This stops 'Run all' at this cell by causing an errot
assert False

# Commented out IPython magic to ensure Python compatibility.
# try out the upload helper function! (I uploaded an image called GENTLE.jpg, upload whatever you want!)
# %cd ..
upload()
# %cd darknet

!./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights ../GENTLE.jpg
imShow('predictions.jpg')

# upload the video of your choosing!
upload()

!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show test.mp4 -i 0 -out_filename results.avi

# download the video with detections shown
download('results.avi')